Lecture/Part6/myproject/models.py
# MODELS.py
from myproject import db
class Puppy(db.Model):
  __tablename__ = 'puppies'
  id = db.Column(db.Integer,primary_key=True)
  name = db.Column(db.Text)
  owner = db.relationship('Owner',backref='puppy',uselist=False)

  def __init__(self,name):
    self.name = name
  
  def __repr__(self):
    if self.owner:
      return f"Puppy is {self.name} belonging to {self.owner.name}"
    else:
      return f"Puppy is {self.name} not registered to owner"

class Owner(db.Model):
  __tablename__ = 'owners'

  id = db.Column(db.Integer,primary_key=True)
  name = db.Column(db.Text)
  puppy_id = db.Column(db.Integer,db.ForeignKey('puppies.id'))

  def __init__(self,name,puppy_id):
    self.name = name
    self.puppy_id = puppy_id
  
  def __repr__(self):
    return f"Owner's name: {self.name}"

Lecture/Part6/myproject/owners/forms.py
# forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField,IntegerField

class AddForm(FlaskForm):
  owner_name = StringField('Name of Owner: ')
  puppy_id = IntegerField('ID of Puppy: ')
  submit = SubmitField('Register Owner')

Lecture/Part6/myproject/puppies/forms.py
# forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField,IntegerField

class AddForm(FlaskForm):
  name = StringField('Name of Puppy: ')
  submit = SubmitField('Add Puppy')

class DeleteForm(FlaskForm):
  id = IntegerField("ID Number of Puppy to Remove: ")
  submit = SubmitField('Remove Puppy')

Lecture/Part6/myproject/__init__.py
import os 
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config['SECRET_KEY'] = 'mykey'

basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir,'data.sqlite')

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

from myproject.puppies.views import puppies_blueprint
from myproject.owners.views import owners_blueprint

app.register_blueprint(owners_blueprint,url_prefix='/owners')

app.register_blueprint(puppies_blueprint,url_prefix='/puppies')

Lecture/Part6/myproject/owners/views.py
from flask import Blueprint,render_template,redirect,url_for, flash
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm

owners_blueprint = Blueprint('owners',__name__,template_folder='templates/owners')

@owners_blueprint.route('/add', methods=['GET','POST'])
def add():
  form = AddForm()

  if form.validate_on_submit():
    owner = Owner(form.owner_name.data,form.puppy_id.data)
    db.session.add(owner)
    db.session.commit()
    flash(f"Owner {owner.name} has been registered")
    return redirect(url_for('puppies.list'))
  
  return render_template('add_owner.html',form=form)

Lecture/Part6/myproject/puppies/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db 
from myproject.puppies.forms import AddForm,DeleteForm
from myproject.models import Puppy

puppies_blueprint = Blueprint('puppies',__name__,template_folder='templates/puppies')

@puppies_blueprint.route('/add',methods=['GET','POST'])
def add():
  form = AddForm()
  if form.validate_on_submit():
    name = form.name.data
    new_pup = Puppy(name)
    db.session.add(new_pup)
    db.session.commit()

    return redirect(url_for('puppies.list'))
  return render_template('add.html', form=form)

@puppies_blueprint.route('/list')
def list():
  puppies = Puppy.query.all()
  return render_template('list.html', puppies=puppies)

@puppies_blueprint.route('/delete',methods=['GET','POST'])
def delete():
  form = DeleteForm()

  if form.validate_on_submit():
    id = form.id.data
    pup = Puppy.query.get(id)
    db.session.delete(pup)
    db.session.commit()
    return redirect(url_for('puppies.list'))
  
  return render_template('delete.html',form=form)

Lecture/Part6/myproject/templates/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>My Site</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="nav-link" href="{{url_for('index')}}">Home</a>
    <a class="nav-link" href="{{url_for('puppies.add')}}">Add Puppies</a>
    <a class="nav-link" href="{{url_for('puppies.list')}}">List Puppies</a>
    <a class="nav-link" href="{{url_for('puppies.delete')}}">Delete Puppies</a>
    <a class="nav-link" href="{{url_for('owners.add')}}">Add Owner</a>
  </nav>
  {% for message in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{message}}
    </div>    
  {% endfor %}

  {% block content %}
  {% endblock %}
</body>
</html>

Lecture/Part6/myproject/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Welcome!</h1>
</div>
{% endblock %}