Project/puppycompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
  title = StringField('Title',validators=[DataRequired()])
  text = TextAreaField('Text',validators=[DataRequired()])
  submit = SubmitField("Post")

Project/puppycompanyblog/blog_posts/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import login_required, current_user
from puppycompanyblog import db
from puppycompanyblog.models import BlogPost
from puppycompanyblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

# CREATE
@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
  form = BlogPostForm()
  if form.validate_on_submit():
    blog_post = BlogPost(form.title.data,
    form.text.data,current_user.id)
    db.session.add(blog_post)
    db.session.commit()
    flash('Blog Post Created')
    return redirect(url_for('core.index'))
  
  return render_template('create_post.html',form=form)

# VIEW
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
  blog_post = BlogPost.query.get_or_404(blog_post_id)
  return render_template('blog_post.html',title=blog_post.title,
  date=blog_post.date,post=blog_post)

# UPDATE
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
  blog_post = BlogPost.query.get_or_404(blog_post_id)
  if blog_post.author != current_user:
    abort(403)
  
  form = BlogPostForm()
  if form.validate_on_submit():
    blog_post.title = form.title.data
    blog_post.text = form.text.data
    db.session.commit()
    flash('Blog Post Updated')
    return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))
  
  elif request.method == 'GET':
    form.title.data = blog_post.title
    form.text.data = blog_post.text

  return render_template('create_post.html',title='Updating',form=form)

# DELETE
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):
  blog_post = BlogPost.query.get_or_404(blog_post_id)
  if blog_post.author != current_user:
    abort(403)
  
  db.session.delete(blog_post)
  db.session.commit()
  flash('Blog Post Deleted')
  return redirect(url_for('core.index'))

Project/puppycompanyblog/core/views.py
from flask import render_template,request,Blueprint
from puppycompanyblog.models import BlogPost
core = Blueprint('core',__name__)

@core.route('/')
def index():
  page = request.args.get('page',1,type=int)
  blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)

  return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():
  return render_template('info.html')

Project/puppycompanyblog/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_required,login_user,logout_user,current_user
from puppycompanyblog import db
from puppycompanyblog.models import User, BlogPost
from puppycompanyblog.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from puppycompanyblog.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

# register
@users.route('/register',methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if form.validate_on_submit():
    user = User(form.email.data,form.username.data,form.password.data)
    db.session.add(user)
    db.session.commit()
    flash('Thanks for Registering!')
    return redirect(url_for('users.login'))
  return render_template('register.html',form=form)

# Login
@users.route('/login',methods=['GET','POST'])
def login():
  form =  LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user is not None and user.check_password(form.password.data):
      login_user(user)
      flash('You Have Been Successfully Logged In')

      next = request.args.get('next')
      if next == None or not next[0] == '/':
        next = url_for('core.index')
      
      return redirect(next)

  return render_template('login.html',form=form)

# Logout
@users.route('/logout')
@login_required
def logout():
  logout_user()
  flash('You Have Been Successfully Logged Out')
  return redirect(url_for('core.index'))

# Account 
@users.route('/account',methods=['GET','POST'])
@login_required
def account():
  form = UpdateUserForm()
  if form.validate_on_submit():
    if form.picture.data:
      username = current_user.username 
      pic = add_profile_pic(form.picture.data,username)
      current_user.profile_image = pic
    
    current_user.username = form.username.data
    current_user.email = form.email.data

    db.session.commit()
    flash('User Account Updated')
    return redirect(url_for('users.account'))
  
  elif request.method == "GET":
    form.username.data = current_user.username
    form.email.data = current_user.email 

  profile_image = url_for('static',filename='profile_pics/' + current_user.profile_image)

  return render_template('account.html',profile_image=profile_image,form=form)
      
# user's list of posts
@users.route('/<username>')
def user_posts(username):
  page = request.args.get('page',1,type=int)
  user = User.query.filter_by(username=username).first_or_404()
  blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
  return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

Project/puppycompanyblog/templates/account.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <div align="center">
      <h1>Welcome to Page For {{current_user.username}}</h1>
      <img src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}" height='200',width='200'>
      <form method="POST" action="" enctype="multipart/form-data">
        <div class="form-group">
          {{form.hidden_tag()}}
        </div>
        <div class="form-group">
        {{form.email.label(class='form-group')}}{{form.email(class='form-control')}}<br>
        </div>
        <div class="form-group">
        {{form.username.label(class='form-group')}}{{form.username(class='form-control')}}<br>
        </div>
        <div class="form-group">
        {{form.picture.label(class='form-group')}}{{form.picture(class='form-control')}}<br>
        </div>
        <div class="form-group">
          {{form.submit(class='btn btn-primary')}}
        </div>
      </form>
    </div>
  </div>
{% endblock %}

Project/puppycompanyblog/templates/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>The Puppy Company</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="nav-link" href="{{url_for('core.index')}}">Home</a>
    <a class="nav-link" href="{{url_for('core.info')}}">About</a>
    {% if current_user.is_authenticated %}
    <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
    <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
    <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
    {% else %}
    <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
    <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
    {% endif %}
  </nav>
  
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

Project/puppycompanyblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>{{post.title}}</h1>
    <h2>Written By: {{post.author.username}}</h2>
    <h3>Published: {{post.date.strftime('%Y-%m-%d')}}</h3>
    <p>{{post.text}}</p>

    {% if post.author == current_user %}
    <div>
      <a href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">Update</a>
      <button type="button" class="btn btn-danger" data-toggle='modal' data-target='#del_modal'>Delete</button>
    </div>
    {% endif %}
  </div>

<div class="modal" tabindex="-1" role="dialog" id='del_modal'>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">

        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

Project/puppycompanyblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Create Post</h1>
    <form class="form-group" method="POST">
      {{form.hidden_tag()}}
      <div class="form-group">
        {{form.title.label(class="form-control-label")}}
        {{form.title(class="form-control")}}
      </div>
      <div class="form-group">
        {{form.text.label(class="form-control-label")}}
        {{form.text(class="form-control")}}        
      </div>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}
      </div>

    </form>
  </div>
{% endblock %}

Project/puppycompanyblog/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Puppy Company Blog</h1>
  </div>

  <div class = "container">
    {% for post in blog_posts.items %}
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{post.title}}</h5>
          <a href="{{url_for('users.user_posts',username=post.author.username)}}">Written By: {{post.author.username}}</a>
          <p>Published On: {{post.date.strftime('%Y-%m-%d')}}</p>
          <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}" class="btn btn-primary">Read Blog Post</a>
        </div>
      </div>
    {% endfor %}
  </div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages() %}
      {% if blog_posts.page == page_num %}
        <li class="page-item disabled"><a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>

{% endblock %}

Project/puppycompanyblog/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Info About Our Company</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
{% endblock %}

Project/puppycompanyblog/templates/login.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <form method="POST">
      {{form.hidden_tag()}}
      {{form.email.label}}{{form.email()}}<br>
      {{form.password.label}}{{form.password()}}<br>
      {{form.submit()}}
    </form>
  </div>
{% endblock %}

Project/puppycompanyblog/templates/register.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <form method="POST">
      {{form.hidden_tag()}}
      {{form.email.label}}{{form.email()}}<br>
      {{form.username.label}}{{form.username()}}<br>
      {{form.password.label}}{{form.password()}}<br>
      {{form.pass_confirm.label}}{{form.pass_confirm()}}<br>
      {{form.submit()}}
    </form>
  </div>
{% endblock %}

Project/puppycompanyblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Page For {{user.username}}</h1>
  </div>

  {% for post in blog_posts.items %}
  <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">
    {{post.title}}
    </a></h2>
  Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>

  <p class="text-muted">Published On: {{post.date.strftime("%Y-%m-%d")}}</p>
  <br>
  <p>{{post.text}}</p>
  <br>
  {% endfor %}
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages() %}
      {% if blog_posts.page == page_num %}
        <li class="page-item disabled"><a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}}</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>

{% endblock %}